# -*- coding: utf-8 -*-
"""Alfred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wKsNj98-wuTgGzoV5KtPrSoS2tsX76Iw
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install langgraph langchain_openai

import os
from typing import TypedDict, List, Dict, Any, Optional
from langgraph.graph import StateGraph, START, END
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage

# Давайте определим, какую информацию Alfred необходимо отслеживать в процессе обработки электронной почты:
class EmailState(TypedDict):
   # Обрабатываемое электронное письмо
    email: Dict[str, Any]  # Содержит тему, отправителя, текст сообщения и т. д.

    # Категория электронного письма (запрос, жалоба и т. д.)
    email_category: Optional[str]

    # Причина, по которой электронное письмо было помечено как спам
    spam_reason: Optional[str]

    # Анализ и принятие решений
    is_spam: Optional[bool]

    # генерация ответа
    email_draft: Optional[str]

    # Обработка метаданных
    messages: List[Dict[str, Any]]  # Отслеживайте переписку с LLM для анализа.

# import os
# from langchain_openai import ChatOpenAI

# # Замените на ваш реальный ключ от OpenAI
# os.environ["OPENAI_API_KEY"] = "key"

# model = ChatOpenAI(temperature=0)

# Commented out IPython magic to ensure Python compatibility.
# %pip install langchain-groq

from langchain_groq import ChatGroq

# Передаем ключ напрямую в аргумент api_key
model = ChatGroq(
    model="llama-3.1-8b-instant",
    temperature=0,
    api_key="key"
)

# Initialize our LLM
model = ChatGroq(
    model="llama-3.1-8b-instant",
    temperature=0,
    api_key="key"
)


def read_email(state: EmailState):
    """Alfred reads and logs the incoming email"""  #Альфред читает и регистрирует входящее электронное письмо.
    email = state["email"]

    # Здесь мы можем выполнить некоторую предварительную обработку.
    print(f"Alfred is processing an email from {email['sender']} with subject: {email['subject']}")

    # Здесь не требуется никаких изменений
    return {}

def classify_email(state: EmailState):
    """Alfred uses an LLM to determine if the email is spam or legitimate"""  #Альфред использует LLM, чтобы определить, является ли электронное письмо спамом или легитимным.
    email = state["email"]

    # Подготавливаем промт для LLM
    prompt = f"""
    As Alfred the butler, analyze this email and determine if it is spam or legitimate.

    Email:
    From: {email['sender']}
    Subject: {email['subject']}
    Body: {email['body']}

    First, determine if this email is spam. If it is spam, explain why.
    If it is legitimate, categorize it (inquiry, complaint, thank you, etc.).
    """

    # Call the LLM
    messages = [HumanMessage(content=prompt)]
    response = model.invoke(messages)

    # Simple logic to parse the response (in a real app, you'd want more robust parsing)
    response_text = response.content.lower()
    is_spam = "spam" in response_text and "not spam" not in response_text

    # Extract a reason if it's spam
    spam_reason = None
    if is_spam and "reason:" in response_text:
        spam_reason = response_text.split("reason:")[1].strip()

    # Determine category if legitimate
    email_category = None
    if not is_spam:
        categories = ["inquiry", "complaint", "thank you", "request", "information"]
        for category in categories:
            if category in response_text:
                email_category = category
                break

    # Update messages for tracking
    new_messages = state.get("messages", []) + [
        {"role": "user", "content": prompt},
        {"role": "assistant", "content": response.content}
    ]

    # Return state updates
    return {
        "is_spam": is_spam,
        "spam_reason": spam_reason,
        "email_category": email_category,
        "messages": new_messages
    }

def handle_spam(state: EmailState):
    """Alfred discards spam email with a note"""
    print(f"Alfred has marked the email as spam. Reason: {state['spam_reason']}")
    print("The email has been moved to the spam folder.")

    # We're done processing this email
    return {}

def draft_response(state: EmailState):
    """Alfred drafts a preliminary response for legitimate emails"""
    email = state["email"]
    category = state["email_category"] or "general"

    # Prepare our prompt for the LLM
    prompt = f"""
    As Alfred the butler, draft a polite preliminary response to this email.

    Email:
    From: {email['sender']}
    Subject: {email['subject']}
    Body: {email['body']}

    This email has been categorized as: {category}

    Draft a brief, professional response that Mr. Hugg can review and personalize before sending.
    """

    # Call the LLM
    messages = [HumanMessage(content=prompt)]
    response = model.invoke(messages)

    # Update messages for tracking
    new_messages = state.get("messages", []) + [
        {"role": "user", "content": prompt},
        {"role": "assistant", "content": response.content}
    ]

    # Return state updates
    return {
        "email_draft": response.content,
        "messages": new_messages
    }

def notify_mr_hugg(state: EmailState):
    """Alfred notifies Mr. Hugg about the email and presents the draft response"""
    email = state["email"]

    print("\n" + "="*50)
    print(f"Sir, you've received an email from {email['sender']}.")
    print(f"Subject: {email['subject']}")
    print(f"Category: {state['email_category']}")
    print("\nI've prepared a draft response for your review:")
    print("-"*50)
    print(state["email_draft"])
    print("="*50 + "\n")

    # We're done processing this email
    return {}

def route_email(state: EmailState) -> str:
    """Determine the next step based on spam classification"""
    if state["is_spam"]:
        return "spam"
    else:
        return "legitimate"

# Create the graph
email_graph = StateGraph(EmailState)

# Add nodes
email_graph.add_node("read_email", read_email)
email_graph.add_node("classify_email", classify_email)
email_graph.add_node("handle_spam", handle_spam)
email_graph.add_node("draft_response", draft_response)
email_graph.add_node("notify_mr_hugg", notify_mr_hugg)

# Start the edges
email_graph.add_edge(START, "read_email")
# Add edges - defining the flow
email_graph.add_edge("read_email", "classify_email")

# Add conditional branching from classify_email
email_graph.add_conditional_edges(
    "classify_email",
    route_email,
    {
        "spam": "handle_spam",
        "legitimate": "draft_response"
    }
)

# Add the final edges
email_graph.add_edge("handle_spam", END)
email_graph.add_edge("draft_response", "notify_mr_hugg")
email_graph.add_edge("notify_mr_hugg", END)

# Compile the graph
compiled_graph = email_graph.compile()

# Example legitimate email
legitimate_email = {
    "sender": "john.smith@example.com",
    "subject": "Question about your services",
    "body": "Dear Mr. Hugg, I was referred to you by a colleague and I'm interested in learning more about your consulting services. Could we schedule a call next week? Best regards, John Smith"
}

# Example spam email
spam_email = {
    "sender": "winner@lottery-intl.com",
    "subject": "YOU HAVE WON $5,000,000!!!",
    "body": "CONGRATULATIONS! You have been selected as the winner of our international lottery! To claim your $5,000,000 prize, please send us your bank details and a processing fee of $100."
}

# Process the legitimate email
print("\nProcessing legitimate email...")
legitimate_result = compiled_graph.invoke({
    "email": legitimate_email,
    "is_spam": None,
    "spam_reason": None,
    "email_category": None,
    "email_draft": None,
    "messages": []
})

# Process the spam email
print("\nProcessing spam email...")
spam_result = compiled_graph.invoke({
    "email": spam_email,
    "is_spam": None,
    "spam_reason": None,
    "email_category": None,
    "email_draft": None,
    "messages": []
})

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q langfuse
# %pip install langchain

import os

# Get keys for your project from the project settings page: https://cloud.langfuse.com
os.environ["LANGFUSE_PUBLIC_KEY"] = "pk-lf-cda146f8-f241-4c28-9f6b-e6e93fbe16b1"
os.environ["LANGFUSE_SECRET_KEY"] = "sk-lf-bd5bac69-9070-4043-9ed7-d3a3b397f130"
os.environ["LANGFUSE_HOST"] = "https://cloud.langfuse.com" # 🇪🇺 EU region
# os.environ["LANGFUSE_HOST"] = "https://us.cloud.langfuse.com" # 🇺🇸 US region

from langfuse.langchain import CallbackHandler

# Initialize Langfuse CallbackHandler for LangGraph/Langchain (tracing)
langfuse_handler = CallbackHandler()

# Process legitimate email
legitimate_result = compiled_graph.invoke(
    input={"email": legitimate_email, "is_spam": None, "spam_reason": None, "email_category": None, "draft_response": None, "messages": []},
    config={"callbacks": [langfuse_handler]}
)

from IPython.display import Image, display

# Get the graph image bytes
image_bytes = compiled_graph.get_graph().draw_mermaid_png()

# Display the image
display(Image(data=image_bytes))

ocaq qfna mnlq nvzt

GMAIL_USER = "rustam04052005@gmail.com"
GMAIL_APP_PASS = "######"  # Ваш пароль приложения без пробелов

import imaplib
import email
from email.header import decode_header

def get_latest_unread_email(username, password):
    # Подключаемся к серверу Gmail
    mail = imaplib.IMAP4_SSL("imap.gmail.com")

    try:
        # Авторизуемся с помощью вашего пароля приложения
        mail.login(username, password)
    except Exception as e:
        print(f"Ошибка авторизации: {e}. Проверьте логин и пароль приложения!")
        return None

    # Выбираем папку "Входящие" (Inbox)
    mail.select("inbox")

    # Ищем только НЕПРОЧИТАННЫЕ (UNSEEN) письма
    status, response = mail.search(None, 'UNSEEN')
    email_ids = response[0].split()

    if not email_ids:
        print("Новых непрочитанных писем нет! Отправьте себе тестовое письмо.")
        mail.logout()
        return None

    # Берем ID самого последнего непрочитанного письма
    latest_email_id = email_ids[-1]

    # Скачиваем данные письма по его ID
    status, format_data = mail.fetch(latest_email_id, '(RFC822)')
    raw_email = format_data[0][1]

    # Превращаем сырые байты в удобный объект сообщения
    msg = email.message_from_bytes(raw_email)

    # 1. Декодируем тему письма
    subject, encoding = decode_header(msg["Subject"])[0]
    if isinstance(subject, bytes):
        subject = subject.decode(encoding or "utf-8", errors="ignore")

    # 2. Декодируем отправителя
    sender, encoding = decode_header(msg["From"])[0]
    if isinstance(sender, bytes):
        sender = sender.decode(encoding or "utf-8", errors="ignore")

    # 3. Достаем текст (тело) письма
    body = ""
    if msg.is_multipart():
        for part in msg.walk():
            content_type = part.get_content_type()
            content_disposition = str(part.get("Content-Disposition"))
            if content_type == "text/plain" and "attachment" not in content_disposition:
                payload = part.get_payload(decode=True)
                body = payload.decode(part.get_content_charset() or "utf-8", errors="ignore")
                break
    else:
        payload = msg.get_payload(decode=True)
        body = payload.decode(msg.get_content_charset() or "utf-8", errors="ignore")

    mail.logout()

    # Возвращаем готовый словарь для нашего LangGraph
    return {
        "sender": sender,
        "subject": subject,
        "body": body.strip()
    }

# --- ПРОВЕРКА ---
# Введите вашу почту и сохраненный 16-значный пароль (без пробелов)
# GMAIL_USER = "ваша_почта@gmail.com"
# GMAIL_APP_PASS = "ваш_16_значный_пароль_приложения"

real_email = get_latest_unread_email(GMAIL_USER, GMAIL_APP_PASS)

if real_email:
    print("\nУспешно прочитано реальное письмо:")
    print(f"От кого: {real_email['sender']}")
    print(f"Тема: {real_email['subject']}")
    print(f"Текст (первые 100 симв.): {real_email['body'][:100]}...")

if real_email:
    print("Передаем реальное письмо Альфреду на анализ...")

    # Запуск графа
    result = compiled_graph.invoke({
        "email": real_email,
        "is_spam": None,
        "spam_reason": None,
        "email_category": None,
        "email_draft": None,
        "messages": []
    })
else:
    print("Нет непрочитанных писем для анализа.")

!pip install smolagents ddgs

from smolagents import DuckDuckGoSearchTool

# Инициализация инструмента поиска DuckDuckGo
search_tool = DuckDuckGoSearchTool()

# Пример использования
results = search_tool( "Кто является нынешним президентом Франции?" )
print (results)